### ISSUE TITLE
Services in Templates

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-05-18/RLee-codes#2]
https://github.com/CodingDojo-MEAN-05-18/RLee-codes/blob/960844cf6d261e4ce5e4f58a12bcc4f4fad607d1/ANGULAR/NinjaGold/src/app/app.component.html#L5-L7

You really don't want to reference your services in your templates. 
Consider creating an instance variable on your component to which you assign gold information. 

https://github.com/CodingDojo-MEAN-05-18/RLee-codes/blob/960844cf6d261e4ce5e4f58a12bcc4f4fad607d1/ANGULAR/NinjaGold/src/app/gold.service.ts#L11

Once you determine that direct assignment doesn't work so well (think about why) turn your gold service variable into a `BehaviorSubject` that streams updated gold data. 

```typescript
 gold$: BehaviorSubject<number> = new BehaviorSubject(0);
```

In your components:

```typescript

ngOnInit() {
  this.goldService.gold$.subscribe(gold => this.gold += gold);
}

```

Other service code will need updating, I'll leave that to you.

**Comment by Unknonymous** [comment]
Thanks!   I'll look into making those changes when I am online tonight.

**Comment by Unknonymous** [comment]
Update:

1. After many frustrating hours and re-watching the lecture portion about Observables, I must admit to frustration at attempting to bend them to our cause in this project.  Perhaps if there is a day/time when you would be able/willing to show me exactly what I am missing, I could set the lines straight in my mind.
2. Having thought about it much & done a little research.  The conclusion of my pondering is that to reference a service directly from the template may expose too much data to the user, thus representing a security vulnerability.  My research led me to a best practices principle for OOP called the Law of Demeter, which essentially states that any unit should access as little data as possible, especially regarding the larger structure of the app.  ...and also this is outside MVC guidelines in which the component mediates between the services and the view.
3. At least I was able to correct the reference to the service in the template by using @Output and passing the data up from the child component, which you should be able to view at your leisure..   although I still would like to get that Observable in place to stream the gold data.  Ideally, I'd like to find a way to use a single observable to pass data to both the parent and sibling components.

**Comment by dojo-json** [comment]
If we solved this problem you should close this issue.

**Comment by Unknonymous** [comment]
We definitely did!  Thanks again for your assistance.
