### ISSUE TITLE
Catch all

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-05-18/RLee-codes#3]
https://github.com/CodingDojo-MEAN-05-18/RLee-codes/blob/b67fd7bfdf5178d7d3c5a9ef25202ac21177d3ed/Integration/IntegrationPractice/server.js#L32-L37

This appears to be similar to the `catch-all` we built during lecture but I don't see it being called so it will never serve the `index.html`

**Comment by Unknonymous** [comment]
I edited the server. js to both export the catch all and also to call it immediately after.   (lines 38 - 40)
After making an additional change to look for index.html at ./AngularApp/dist/AngularApp/index.html, the server makes the attempt to serve the file, but does not seem to render any html content.

module.exports = function (app) {
    app.all("*", (req, res, next) => {
        res.sendFile(path.resolve("./AngularApp/dist/AngularApp/index.html"));
    });
};

app.all("*", (req, res, next) => {
    res.sendFile(path.resolve("./AngularApp/dist/AngularApp/index.html"));
});

If I enter plain text into the index.html, it is shown, but any html content is met with "Uncaught SyntaxError: Unexpected token < " , in the console.

![image](https://user-images.githubusercontent.com/34700342/43040986-4adad274-8d21-11e8-8e17-d9d3f0a6b235.png)
![image](https://user-images.githubusercontent.com/34700342/43041013-1f8035be-8d22-11e8-9452-dc234398bdf4.png)

**Comment by dojo-json** [comment]
Strange. I'll pull your repo and take a look today.

**Comment by dojo-json** [comment]
https://github.com/CodingDojo-MEAN-05-18/RLee-codes/blob/9f052d5660283078c7029eca6045f58116de7ccb/Integration/IntegrationPractice/server.js#L9-L12

typo in the static content you are serving


After you fix that you'll find an Angular routing error.

**Comment by Unknonymous** [comment]
Hah!  Thanks!   I fixed the typo and the routing error.     ...and suddenly I've got content appearing.  It's late now, but I can't wait to get  back at it tomorrow after work!
