### ISSUE TITLE
Declarations

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-05-18/RLee-codes#5]
https://github.com/CodingDojo-MEAN-05-18/RLee-codes/blob/b67fd7bfdf5178d7d3c5a9ef25202ac21177d3ed/Integration/IntegrationPractice/server.js#L1-L7

Consider always using the newer declarations rather than `var`. Whichever you choose, be consistent.

**Comment by Unknonymous** [comment]
Yes, definitely.   Thank you.  
I'm sure I meant to use 'const' there as I can clearly recall you advising us that 'var' was not going to cut it on the exam.   ...habits.     I've fixed them.
