### ISSUE TITLE
Serving Index

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-05-18/RLee-codes#6]
https://github.com/CodingDojo-MEAN-05-18/RLee-codes/blob/cbc44f249af2ae2dd8a0d84ff12af6cd4ea0a472/Integration/IntegrationPractice/server.js#L8-L12

Sorry, I missed this yesterday. When serving your static content you are current referencing your `Angularapp/dist` directory. Be aware that you need to reference a relative path with `./`. It is currently absolute, which means it is looking for this content in the root of your filesystem. Also note that Unix based systems (Ubunutu deployment server, OSX, etc) are case sensitive, so `Angularpp` needs to be `AngularApp`. Updating that would be sufficient if you were using Angular versions < 6. Now when compiling it will create a nested dir inside `dist` of the applications name by default. You can change this to whatever you like by opening `angular.json` and modifying `outputPath`.

https://github.com/CodingDojo-MEAN-05-18/RLee-codes/blob/cbc44f249af2ae2dd8a0d84ff12af6cd4ea0a472/Integration/IntegrationPractice/AngularApp/angular.json#L13-L18

Good for future use, but I imagine you just want it to work now. 
Using this line to serve static content should get you moving in the right direction. 
```javascript
 app.use(express.static(path.join(__dirname, './AngularApp/dist/AngularApp'))); 
```

**Comment by Unknonymous** [comment]
This was a great catch.  I must have looked at this a dozen times without actually seeing it.   Thanks Jason!
